exports.ingredients = [
    {name: 'Ground Beef', category: 'Meat'},
    {name: 'Milk', category: 'Dairy'},
    {name: 'Ground Pork', category: 'Meat'},
    {name: 'Ground Veal', category: 'Meat'},
    {name: 'Onion', category: 'Vegetable'},
    {name: 'Egg', category: 'Meat'},
    {name: 'Bread Crumbs', category: 'Bakery'},
    {name: 'Garlic', category: 'Vegetable'},
    {name: 'Parmesan', category: 'Dairy'},
    {name: 'Basil', category: 'Herb'},
    {name: 'Oregano', category: 'Herb'},
    {name: 'Baby Red Potatoes', category: 'Vegetable'},
    {name: 'Olive Oil', category: 'Fat'},
    {name: 'Parsley', category: 'Herb'},
    {name: 'Sea Salt', category: 'Seasoning'},
    {name: 'Ground Pepper', category: 'Seasoning'},
    {name: 'Garlic', category: 'Vegetable'},
    {name: 'Tomatoes',category:	'Vegetable'},
    {name: 'Mozzarella',category:'Cheese'},
    {name: 'Balsamic Vinegar',category:'Condiment'},
    {name: 'Salmon Filet', category: 'Fish'},
    {name: 'Lemon Juice', category: 'Juice'},
    {name: 'Dijon Mustard', category: 'Condiment'},
    {name: 'Lemon', category:'Fruit'},
    {name: 'Bacon', category: 'Meat'},
    {name: 'Potato', category:'Vegetable'},
    {name: 'Baby Spinach', category: 'Herb'},
    {name: 'Cheddar', category: 'Cheese'},
    {name: 'Cream', category:'Dairy'},
    {name: 'Tabasco', category:'Condiment'}
]

exports.recipes = [
    {name: 'Spaghetti and Meatballs', category: 'Pasta', prepTime: '40', ingredients: [], directions: '' ,image: 'https://i.imgur.com/GlAYOFk.jpeg'},
    {name: 'Caprese Salad', category: 'Salad', prepTime: '20', ingredients: [], directions: '', image: 'https://i.imgur.com/AslAYGx.jpeg' },
    {name: 'Baked Salmon with Garlic and Dijon', category: 'Seafood', prepTime: '40', ingredients: [], directions: '', image: 'https://i.imgur.com/HoopkDu.jpeg' },
    {name: 'Breakfast Egg Muffins', category: 'Breakfast', prepTime: '30', ingredients: [], directions: '' ,image: 'https://i.imgur.com/rgaw8Hu.jpeg'},
    {name: 'Oven Roasted Baby Potatoes', category: '', prepTime: '50', ingredients: [], directions: '', image: 'https://i.imgur.com/CZsFFvs.jpeg' }
]